curl -X POST http://localhost:8080/api/zip/springboot \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "javaVersion=17" \
  -d "name=HelloWorld" \
  -d "groupId=com.mr486" \
  -d "artifactId=hello" \
  -d "version=0.0.1-SNAPSHOT" \
  -d "dependencies=web" \
  -d "localPort=8080" \
  -d "dockerPort=9000" \
  --output springboot.zip