services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    container_name: service-a
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    container_name: service-b
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

